### ISSUE TITLE
Error create database

### ISSUE THREAD

**Issue by yuserly** [webreinvent/laravel-cpanel#2]
They domain value does not pass, ir comes as a response: https://:port/execute....

**Comment by themodernpk** [comment]
@yuserly Can you share the complete formatted response?

**Comment by yuserly** [comment]
response

{
"status": "success",
"data": null,
"inputs": {
"url": "https://:2083/execute/Mysql/create_database?&name=name_name"
}
}

my .env

CPANEL_DOMAIN= xxxxxx
CPANEL_PORT=2083
CPANEL_API_TOKEN=xxxxxx
CPANEL_USERNAME= xxxxxxxx

**Comment by themodernpk** [comment]
Did you run the following command after the package installation? 
```
php artisan vendor:publish --provider="WebReinvent\CPanel\CPanelServiceProvider" --tag=config
```

**Comment by yuserly** [comment]
yes, and the problem continues.

**Comment by themodernpk** [comment]
@yuserly I have verified the package with a fresh laravel installation, everything seems working as intended. You can also verify the package with fresh laravel installation. 

You should verify env parameters are properly loaded and make sure you clear all the laravel cache.
