### ISSUE TITLE
Unable to publish Config.

### ISSUE THREAD

**Issue by anantgrafix** [webreinvent/laravel-cpanel#4]
```
D:\xampp\htdocs\internalpanel\landlord>php artisan vendor:publish --provider="WebReinvent\CPanel\CPanelServiceProvi
der" --tag=config
Unable to locate publishable resources.
```

**Comment by themodernpk** [comment]
@anantgrafix looks like you did not followed step 2, which is:

#### Step 2) Register the ServiceProvider
Add following service provider in `config/app.php`  
```php  
/*  
 * Package Service Providers...  
 */ 
 'providers' => [  
        //...  
        WebReinvent\CPanel\CPanelServiceProvider::class,   
        //...  
    ],
```

I have tested the package on fresh laravel installation and it worked perfectly fine.

**Comment by anantgrafix** [comment]
I thought Laravel 8 will Automatically detects Service Providers in packages. Sorry.
